name: banksampah
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  son_to_model: ^1.3.13
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
  image_picker: ^0.6.2+3
  shared_preferences: ^0.5.3+4
  line_icons: ^0.2.0
  package_info: ^0.4.0+6
  cached_network_image: ^2.0.0 
  sqflite: ^1.3.1
  intl: 
  http:
  qr_flutter: ^3.0.1
  google_sign_in: ^4.0.0
  path_provider: ^1.6.10
  flutter_offline: "^0.3.0"
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - img/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700